services:
  backend: &backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 6001:3000
    volumes:
      - .:/var/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
